translator_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("translators/", include("translators.urls"))
]

translators/urls.py
from django.urls import path
from .views import language_detail, front_view, search_out, KeyCreate, LanguageList, LanguageCreate, WordCreate


urlpatterns = [
    path("languages/", LanguageList.as_view(), name="list_languages" ),
    path("languages/<int:pk>/", language_detail, name="detail_languages"),
    path("add_languages/", LanguageCreate.as_view(), name="add_languages"),
    path("add_words/", WordCreate.as_view(), name="add_words"),
    path("searched/", search_out, name="search_out"),
    path("", front_view, name="front_view" ),
    path("add_keys/", KeyCreate.as_view(), name="add_keys"),
]

numberfy/models.py
from django.db import models

class Entry(models.Model):
    entries = models.PositiveIntegerField()

class Simplify(models.Model):
    entries = models.ForeignKey(
        "Entry", related_name="simplifys",
        on_delete=models.CASCADE)

translators/models.py
from django.db import models
from .managers import TransManager

# class Entry(models.Model):
#     entries = models.CharField(max_length=15)
#     types = models.ForeignKey(
#         "Type", related_name="entries_type", on_delete=models.CASCADE)

class Language(models.Model):
    name = models.CharField(max_length=15, unique=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)

    objects = TransManager()

    def __str__(self):
        return f"{str(self.name)}"

class Word(models.Model):
    words = models.CharField(max_length=20, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    languages = models.ForeignKey(
        "Language", related_name="words", on_delete=models.CASCADE)

    objects = TransManager()

    def __str__(self):
        return f"{str(self.words)}"


class Type(models.Model):
    types = models.CharField(max_length=20, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)

    objects = TransManager()

    def __str__(self):
        return f"{str(self.types)}"


class Key(models.Model):
    homes = models.ForeignKey(
        "Word", related_name="keys_home", on_delete=models.CASCADE)
    aways = models.ForeignKey(
        "Word", related_name="keys_away", on_delete=models.CASCADE)
    types = models.ForeignKey(
        "Type", related_name="keys_type", on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)

    objects = TransManager()

    def __str__(self):
        return f"{str(self.homes)} {str(self.types)} {str(self.aways)}"

numberfy/views.py
from django.shortcuts import render

# Create your views here.

translators/views.py
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView
from .models import Language, Word, Key, Type
from django.urls import reverse_lazy


# def show_recipe(request, pk):
#     context = {
#         "recipe": Recipe.objects.get(pk=pk) if Recipe else None,
#         "rating_form": RatingForm(),  # highlight
#     }
#     return render(request, "recipes/detail.html", context)

# def key_list(request, home, type):
#     key_words = Key.objects.get_keys(home, type)
#     context = {
#         "key_words": key_words
#     }
#     return render(request, "translators/entry/out.html", context)

def search_out(request):
    print("hello")
    type_value = ""
    home_value = ""
    keys_list = ""
    if request.method == "POST":
        searched = list(request.POST["searched"])
        length = len(searched)

        for i in range(length):
            if searched[i] in Type.objects.all():
                type_char = searched.pop(i)
                type_value.append(type_char)
        home_value= "".join(searched)


        # x = Key.objects.filter(homes=home_value)
        # print(f"{x}")
        # home_words = Word.objects.get_words_test()



        if type_value == "":
            print(f"{home_value} if type_value == "":")

            # keys = Word.objects.get(words=home_value)
            keys_list = Key.objects.get_only_words(home_value)
        # else:
        #     keys_list = Word.objects.get_keys(home_value, type_value)

    context = {"keys_list": keys_list}
    print(keys_list)
    print("mynameisandreeeeew")
    # print(type(home_value))
    # print(type_value)
    # print(type(type_value))
    return render(request, "translators/search/search_out.html", context)


def language_detail(request, pk):
    language = Language.objects.get(pk=pk)
    # print(f"{type(language)}   language = Language.objects.get(pk=pk) ")
    lang_words = Word.objects.get_words(language)
    context = {
        "lang_words": lang_words
    }
    return render(request, "translators/languages/detail.html", context)


def front_view(request):
    language = Language.objects.get_latest("date_added")
    words = Word.objects.get_latest("date_added")
    types = Type.objects.get_latest("date_added")
    keys = Key.objects.get_latest("date_added")
    # lang_dated = getattr(language, "date_added")
    # words_dated = getattr(words, "date_added")
    # types_dated = getattr(types, "date_added")
    # keys_dated = getattr(keys, "date_added")
    context = {
        "language": language,
        "words": words,
        "types": types,
        "keys": keys,
    }
    return render(request, "translators/front.html", context)

class LanguageList(ListView):
    model = Language
    template_name = "translators/languages/list.html"

class LanguageCreate(CreateView):
    model = Language
    fields = [
        "name",
    ]
    template_name = "translators/languages/create.html"
    success_url = reverse_lazy("add_words")

class KeyCreate(CreateView):
    model = Key
    fields = [
        "homes",
        "aways",
        "types",
    ]
    template_name= "translators/keys/create.html"
    success_url = reverse_lazy("front_view")

class WordCreate(CreateView):
    model = Word
    fields = [
        "languages",
        "words",
    ]
    template_name = "translators/words/create.html"
    success_url = reverse_lazy("list_languages")

# class EntryCreate(CreateView):
#     model = Entry
#     fields = [
#         "entries"
#     ]
#     template_name = "translators/entry/create.html"
#     success_url = reverze_lazy("fdsafd", home, type)

translators/templates/translators/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Input Entry</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <header>
        <nav>
        <ul>
            <li>
                <form method="POST" action="{% url 'search_out' %}">
                    {% csrf_token %}
                    <input type="search" name="searched" placeholder="Search..." >
                      <button type="submit">Search</button>
                </form>
            </li>
            <li>
                <a href="{% url 'list_languages'%}">List of Languages</a>
            </li>
            <li>
                <a href="{% url 'add_languages'%}">Add languages</a>
            </li>
            <li>
                <a href="{% url 'add_words'%}">Add Words</a>
            </li>
            <li>
                <a href="{% url 'add_keys'%}">Add Keys</a>
            </li>
            <li>
                <a href="{% url 'front_view'%}">Home Sweet Home</a>
            </li>
        </ul>

        </nav>
    </header>
{% block content %}
{% endblock %}
</body>
</html>

translators/templates/translators/entry/create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Input Entry</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        {% comment %} <li>
          <a href="{% url 'home' %}">Scrumptious</a>
        </li>
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li>
          <a href="{% url 'recipe_new' %}">Write a recipe</a> {% endcomment %}
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <div>
      <form>
        <input type="search" placeholder="Search" araia-label="Search">
        <button type="submit">Search</button>
      </form>
    </div>
  </main>
</body>

</html>

translators/templates/translators/entry/out.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Language Words</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <main>
        <header>
            <ul>
                {% comment %} {% for words in lang_words %}
                    <li>
                    {{ words }}
                    </li>
                {% endfor %} {% endcomment %}
            </ul>
        </header>
  </main>
</body>

</html>

translators/templates/translators/front.html
{% extends "translators/base.html" %}

{% block content  %}
<main>
    <ul>
        <li>"{{ language }} to Languages on {{ language.date_added }}"</li>
        <li>"{{ words }} to Words on {{ words.date_added }}"</li>
        <li>"{{ types }} added to Types on {{ types.date_added }}"</li>
        <li>"{{ keys }} added to Keys on {{ keys.date_added }}"</li>
    </ul>
</main>
{% endblock  %}

translators/templates/translators/keys/create.html
{% extends "translators/base.html" %}

{% block content%}

<main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock %}

translators/templates/translators/languages/create.html
{% extends "translators/base.html" %}

{% block content  %}
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock  %}

translators/templates/translators/languages/detail.html
{% extends "translators/base.html" %}

{% block content  %}

    <ul>

        {% for words in lang_words %}

            <li>
            {{ words }}
            </li>

        {% endfor %}
    </ul>
{% endblock  %}

translators/templates/translators/languages/list.html
{% extends "translators/base.html" %}

{% block content  %}

  <ul>
    {% for language in language_list %}
    <div >
        <li>
        <a href="{% url 'detail_languages' language.pk %}">{{ language.name }}</a>
        </li>
    </div>
    {% endfor %}
  </ul>

{% endblock  %}

translators/templates/translators/search/search_out.html
{% extends "translators/base.html" %}

{% block content %}
    <main>
        {% if searched %}
            <h1>You Searched: {{searched}}</h1>
        {% else %}
            <h1>Hey! You forgot to enter into the search bar!</h1>
        {% endif %}
        <h2>
            This is what I found:
        </h2>
        <h3>
            <ul>
                {% for keys in keys_list %}
                <div>
                    <li>
                        {{ keys }}
                    </li>
                </div>
                {% endfor %}
            </ul>
        </h3>
    </main>
{% endblock  %}

translators/templates/translators/words/create.html
{% extends "translators/base.html" %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock  %}